/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package etudiant.model.impl;

import etudiant.model.Etudiant;

import etudiant.service.EtudiantLocalServiceUtil;

/**
 * The extended model base implementation for the Etudiant service. Represents a row in the &quot;LL_Etudiant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EtudiantImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EtudiantImpl
 * @see Etudiant
 * @generated
 */
public abstract class EtudiantBaseImpl
	extends EtudiantModelImpl implements Etudiant {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a etudiant model instance should use the <code>Etudiant</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EtudiantLocalServiceUtil.addEtudiant(this);
		}
		else {
			EtudiantLocalServiceUtil.updateEtudiant(this);
		}
	}

}