/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package classe.model.impl;

import classe.model.Classe;
import classe.model.ClasseModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Classe service. Represents a row in the &quot;LL_Classe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ClasseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClasseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClasseImpl
 * @generated
 */
@JSON(strict = true)
public class ClasseModelImpl
	extends BaseModelImpl<Classe> implements ClasseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a classe model instance should use the <code>Classe</code> interface instead.
	 */
	public static final String TABLE_NAME = "LL_Classe";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"classeId", Types.BIGINT},
		{"Intitule", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("classeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Intitule", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LL_Classe (uuid_ VARCHAR(75) null,classeId LONG not null primary key,Intitule VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LL_Classe";

	public static final String ORDER_BY_JPQL = " ORDER BY classe.classeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LL_Classe.classeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ClasseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _classeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setClasseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _classeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Classe.class;
	}

	@Override
	public String getModelClassName() {
		return Classe.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Classe, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Classe, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Classe, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Classe)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Classe, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Classe, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Classe)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Classe, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Classe, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Classe, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Classe, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Classe, Object>>();

			attributeGetterFunctions.put("uuid", Classe::getUuid);
			attributeGetterFunctions.put("classeId", Classe::getClasseId);
			attributeGetterFunctions.put("Intitule", Classe::getIntitule);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Classe, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Classe, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Classe, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Classe, String>)Classe::setUuid);
			attributeSetterBiConsumers.put(
				"classeId", (BiConsumer<Classe, Long>)Classe::setClasseId);
			attributeSetterBiConsumers.put(
				"Intitule", (BiConsumer<Classe, String>)Classe::setIntitule);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getClasseId() {
		return _classeId;
	}

	@Override
	public void setClasseId(long classeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classeId = classeId;
	}

	@JSON
	@Override
	public String getIntitule() {
		if (_Intitule == null) {
			return "";
		}
		else {
			return _Intitule;
		}
	}

	@Override
	public void setIntitule(String Intitule) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Intitule = Intitule;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Classe.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Classe toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Classe>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ClasseImpl classeImpl = new ClasseImpl();

		classeImpl.setUuid(getUuid());
		classeImpl.setClasseId(getClasseId());
		classeImpl.setIntitule(getIntitule());

		classeImpl.resetOriginalValues();

		return classeImpl;
	}

	@Override
	public Classe cloneWithOriginalValues() {
		ClasseImpl classeImpl = new ClasseImpl();

		classeImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		classeImpl.setClasseId(this.<Long>getColumnOriginalValue("classeId"));
		classeImpl.setIntitule(this.<String>getColumnOriginalValue("Intitule"));

		return classeImpl;
	}

	@Override
	public int compareTo(Classe classe) {
		long primaryKey = classe.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Classe)) {
			return false;
		}

		Classe classe = (Classe)object;

		long primaryKey = classe.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Classe> toCacheModel() {
		ClasseCacheModel classeCacheModel = new ClasseCacheModel();

		classeCacheModel.uuid = getUuid();

		String uuid = classeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			classeCacheModel.uuid = null;
		}

		classeCacheModel.classeId = getClasseId();

		classeCacheModel.Intitule = getIntitule();

		String Intitule = classeCacheModel.Intitule;

		if ((Intitule != null) && (Intitule.length() == 0)) {
			classeCacheModel.Intitule = null;
		}

		return classeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Classe, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Classe, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Classe, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Classe)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Classe>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Classe.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _classeId;
	private String _Intitule;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Classe, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Classe)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("classeId", _classeId);
		_columnOriginalValues.put("Intitule", _Intitule);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("classeId", 2L);

		columnBitmasks.put("Intitule", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Classe _escapedModel;

}