/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package classe.model.impl;

import classe.model.Classe;

import classe.service.ClasseLocalServiceUtil;

/**
 * The extended model base implementation for the Classe service. Represents a row in the &quot;LL_Classe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClasseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClasseImpl
 * @see Classe
 * @generated
 */
public abstract class ClasseBaseImpl extends ClasseModelImpl implements Classe {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a classe model instance should use the <code>Classe</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ClasseLocalServiceUtil.addClasse(this);
		}
		else {
			ClasseLocalServiceUtil.updateClasse(this);
		}
	}

}