/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package matiere.model.impl;

import matiere.model.Matiere;

import matiere.service.MatiereLocalServiceUtil;

/**
 * The extended model base implementation for the Matiere service. Represents a row in the &quot;LL_Matiere&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MatiereImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MatiereImpl
 * @see Matiere
 * @generated
 */
public abstract class MatiereBaseImpl
	extends MatiereModelImpl implements Matiere {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a matiere model instance should use the <code>Matiere</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MatiereLocalServiceUtil.addMatiere(this);
		}
		else {
			MatiereLocalServiceUtil.updateMatiere(this);
		}
	}

}