/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package etudiant.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Etudiant service. Represents a row in the &quot;LL_Etudiant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>etudiant.model.impl.EtudiantModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>etudiant.model.impl.EtudiantImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Etudiant
 * @generated
 */
@ProviderType
public interface EtudiantModel extends BaseModel<Etudiant> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a etudiant model instance should use the {@link Etudiant} interface instead.
	 */

	/**
	 * Returns the primary key of this etudiant.
	 *
	 * @return the primary key of this etudiant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this etudiant.
	 *
	 * @param primaryKey the primary key of this etudiant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this etudiant.
	 *
	 * @return the uuid of this etudiant
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this etudiant.
	 *
	 * @param uuid the uuid of this etudiant
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the etudiant ID of this etudiant.
	 *
	 * @return the etudiant ID of this etudiant
	 */
	public long getEtudiantId();

	/**
	 * Sets the etudiant ID of this etudiant.
	 *
	 * @param etudiantId the etudiant ID of this etudiant
	 */
	public void setEtudiantId(long etudiantId);

	/**
	 * Returns the nom of this etudiant.
	 *
	 * @return the nom of this etudiant
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this etudiant.
	 *
	 * @param nom the nom of this etudiant
	 */
	public void setNom(String nom);

	/**
	 * Returns the prenom of this etudiant.
	 *
	 * @return the prenom of this etudiant
	 */
	@AutoEscape
	public String getPrenom();

	/**
	 * Sets the prenom of this etudiant.
	 *
	 * @param prenom the prenom of this etudiant
	 */
	public void setPrenom(String prenom);

	/**
	 * Returns the image ID of this etudiant.
	 *
	 * @return the image ID of this etudiant
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this etudiant.
	 *
	 * @param imageId the image ID of this etudiant
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the classe ID of this etudiant.
	 *
	 * @return the classe ID of this etudiant
	 */
	public long getClasseId();

	/**
	 * Sets the classe ID of this etudiant.
	 *
	 * @param classeId the classe ID of this etudiant
	 */
	public void setClasseId(long classeId);

	@Override
	public Etudiant cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}