/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package matiere.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Matiere service. Represents a row in the &quot;LL_Matiere&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>matiere.model.impl.MatiereModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>matiere.model.impl.MatiereImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Matiere
 * @generated
 */
@ProviderType
public interface MatiereModel extends BaseModel<Matiere> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a matiere model instance should use the {@link Matiere} interface instead.
	 */

	/**
	 * Returns the primary key of this matiere.
	 *
	 * @return the primary key of this matiere
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this matiere.
	 *
	 * @param primaryKey the primary key of this matiere
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this matiere.
	 *
	 * @return the uuid of this matiere
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this matiere.
	 *
	 * @param uuid the uuid of this matiere
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the matiere ID of this matiere.
	 *
	 * @return the matiere ID of this matiere
	 */
	public long getMatiereId();

	/**
	 * Sets the matiere ID of this matiere.
	 *
	 * @param matiereId the matiere ID of this matiere
	 */
	public void setMatiereId(long matiereId);

	/**
	 * Returns the classe ID of this matiere.
	 *
	 * @return the classe ID of this matiere
	 */
	public long getClasseId();

	/**
	 * Sets the classe ID of this matiere.
	 *
	 * @param classeId the classe ID of this matiere
	 */
	public void setClasseId(long classeId);

	/**
	 * Returns the professeur ID of this matiere.
	 *
	 * @return the professeur ID of this matiere
	 */
	public long getProfesseurId();

	/**
	 * Sets the professeur ID of this matiere.
	 *
	 * @param professeurId the professeur ID of this matiere
	 */
	public void setProfesseurId(long professeurId);

	/**
	 * Returns the intitule of this matiere.
	 *
	 * @return the intitule of this matiere
	 */
	@AutoEscape
	public String getIntitule();

	/**
	 * Sets the intitule of this matiere.
	 *
	 * @param Intitule the intitule of this matiere
	 */
	public void setIntitule(String Intitule);

	@Override
	public Matiere cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}