/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package professeur.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import professeur.model.ProfClasse;
import professeur.model.ProfClasseModel;

/**
 * The base model implementation for the ProfClasse service. Represents a row in the &quot;LL_ProfClasse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProfClasseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProfClasseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProfClasseImpl
 * @generated
 */
@JSON(strict = true)
public class ProfClasseModelImpl
	extends BaseModelImpl<ProfClasse> implements ProfClasseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prof classe model instance should use the <code>ProfClasse</code> interface instead.
	 */
	public static final String TABLE_NAME = "LL_ProfClasse";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"profClasseId", Types.BIGINT},
		{"professeurId", Types.BIGINT}, {"classeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("profClasseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("professeurId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LL_ProfClasse (uuid_ VARCHAR(75) null,profClasseId LONG not null primary key,professeurId LONG,classeId LONG)";

	public static final String TABLE_SQL_DROP = "drop table LL_ProfClasse";

	public static final String ORDER_BY_JPQL =
		" ORDER BY profClasse.profClasseId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LL_ProfClasse.profClasseId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROFESSEURID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROFCLASSEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProfClasseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _profClasseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProfClasseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _profClasseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProfClasse.class;
	}

	@Override
	public String getModelClassName() {
		return ProfClasse.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProfClasse, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProfClasse, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProfClasse, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ProfClasse)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProfClasse, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProfClasse, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProfClasse)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProfClasse, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProfClasse, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ProfClasse, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ProfClasse, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<ProfClasse, Object>>();

			attributeGetterFunctions.put("uuid", ProfClasse::getUuid);
			attributeGetterFunctions.put(
				"profClasseId", ProfClasse::getProfClasseId);
			attributeGetterFunctions.put(
				"professeurId", ProfClasse::getProfesseurId);
			attributeGetterFunctions.put("classeId", ProfClasse::getClasseId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ProfClasse, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ProfClasse, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ProfClasse, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<ProfClasse, String>)ProfClasse::setUuid);
			attributeSetterBiConsumers.put(
				"profClasseId",
				(BiConsumer<ProfClasse, Long>)ProfClasse::setProfClasseId);
			attributeSetterBiConsumers.put(
				"professeurId",
				(BiConsumer<ProfClasse, Long>)ProfClasse::setProfesseurId);
			attributeSetterBiConsumers.put(
				"classeId",
				(BiConsumer<ProfClasse, Long>)ProfClasse::setClasseId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProfClasseId() {
		return _profClasseId;
	}

	@Override
	public void setProfClasseId(long profClasseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_profClasseId = profClasseId;
	}

	@JSON
	@Override
	public long getProfesseurId() {
		return _professeurId;
	}

	@Override
	public void setProfesseurId(long professeurId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_professeurId = professeurId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProfesseurId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("professeurId"));
	}

	@JSON
	@Override
	public long getClasseId() {
		return _classeId;
	}

	@Override
	public void setClasseId(long classeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classeId = classeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClasseId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classeId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ProfClasse.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProfClasse toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProfClasse>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProfClasseImpl profClasseImpl = new ProfClasseImpl();

		profClasseImpl.setUuid(getUuid());
		profClasseImpl.setProfClasseId(getProfClasseId());
		profClasseImpl.setProfesseurId(getProfesseurId());
		profClasseImpl.setClasseId(getClasseId());

		profClasseImpl.resetOriginalValues();

		return profClasseImpl;
	}

	@Override
	public ProfClasse cloneWithOriginalValues() {
		ProfClasseImpl profClasseImpl = new ProfClasseImpl();

		profClasseImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		profClasseImpl.setProfClasseId(
			this.<Long>getColumnOriginalValue("profClasseId"));
		profClasseImpl.setProfesseurId(
			this.<Long>getColumnOriginalValue("professeurId"));
		profClasseImpl.setClasseId(
			this.<Long>getColumnOriginalValue("classeId"));

		return profClasseImpl;
	}

	@Override
	public int compareTo(ProfClasse profClasse) {
		long primaryKey = profClasse.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProfClasse)) {
			return false;
		}

		ProfClasse profClasse = (ProfClasse)object;

		long primaryKey = profClasse.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProfClasse> toCacheModel() {
		ProfClasseCacheModel profClasseCacheModel = new ProfClasseCacheModel();

		profClasseCacheModel.uuid = getUuid();

		String uuid = profClasseCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			profClasseCacheModel.uuid = null;
		}

		profClasseCacheModel.profClasseId = getProfClasseId();

		profClasseCacheModel.professeurId = getProfesseurId();

		profClasseCacheModel.classeId = getClasseId();

		return profClasseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProfClasse, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProfClasse, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProfClasse, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ProfClasse)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProfClasse>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProfClasse.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _profClasseId;
	private long _professeurId;
	private long _classeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProfClasse, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProfClasse)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("profClasseId", _profClasseId);
		_columnOriginalValues.put("professeurId", _professeurId);
		_columnOriginalValues.put("classeId", _classeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("profClasseId", 2L);

		columnBitmasks.put("professeurId", 4L);

		columnBitmasks.put("classeId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProfClasse _escapedModel;

}