/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package professeur.model.impl;

import professeur.model.ProfClasse;

import professeur.service.ProfClasseLocalServiceUtil;

/**
 * The extended model base implementation for the ProfClasse service. Represents a row in the &quot;LL_ProfClasse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProfClasseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProfClasseImpl
 * @see ProfClasse
 * @generated
 */
public abstract class ProfClasseBaseImpl
	extends ProfClasseModelImpl implements ProfClasse {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prof classe model instance should use the <code>ProfClasse</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProfClasseLocalServiceUtil.addProfClasse(this);
		}
		else {
			ProfClasseLocalServiceUtil.updateProfClasse(this);
		}
	}

}