/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package professeur.model.impl;

import professeur.model.Professeur;

import professeur.service.ProfesseurLocalServiceUtil;

/**
 * The extended model base implementation for the Professeur service. Represents a row in the &quot;LL_Professeur&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProfesseurImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProfesseurImpl
 * @see Professeur
 * @generated
 */
public abstract class ProfesseurBaseImpl
	extends ProfesseurModelImpl implements Professeur {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a professeur model instance should use the <code>Professeur</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProfesseurLocalServiceUtil.addProfesseur(this);
		}
		else {
			ProfesseurLocalServiceUtil.updateProfesseur(this);
		}
	}

}