/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package professeur.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import professeur.model.Professeur;
import professeur.model.ProfesseurModel;

/**
 * The base model implementation for the Professeur service. Represents a row in the &quot;LL_Professeur&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProfesseurModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProfesseurImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProfesseurImpl
 * @generated
 */
@JSON(strict = true)
public class ProfesseurModelImpl
	extends BaseModelImpl<Professeur> implements ProfesseurModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a professeur model instance should use the <code>Professeur</code> interface instead.
	 */
	public static final String TABLE_NAME = "LL_Professeur";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"professeurId", Types.BIGINT},
		{"nom", Types.VARCHAR}, {"prenom", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("professeurId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nom", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prenom", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LL_Professeur (uuid_ VARCHAR(75) null,professeurId LONG not null primary key,nom VARCHAR(75) null,prenom VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LL_Professeur";

	public static final String ORDER_BY_JPQL =
		" ORDER BY professeur.professeurId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LL_Professeur.professeurId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROFESSEURID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProfesseurModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _professeurId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProfesseurId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _professeurId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Professeur.class;
	}

	@Override
	public String getModelClassName() {
		return Professeur.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Professeur, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Professeur, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Professeur, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Professeur)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Professeur, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Professeur, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Professeur)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Professeur, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Professeur, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Professeur, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Professeur, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Professeur, Object>>();

			attributeGetterFunctions.put("uuid", Professeur::getUuid);
			attributeGetterFunctions.put(
				"professeurId", Professeur::getProfesseurId);
			attributeGetterFunctions.put("nom", Professeur::getNom);
			attributeGetterFunctions.put("prenom", Professeur::getPrenom);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Professeur, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Professeur, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Professeur, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Professeur, String>)Professeur::setUuid);
			attributeSetterBiConsumers.put(
				"professeurId",
				(BiConsumer<Professeur, Long>)Professeur::setProfesseurId);
			attributeSetterBiConsumers.put(
				"nom", (BiConsumer<Professeur, String>)Professeur::setNom);
			attributeSetterBiConsumers.put(
				"prenom",
				(BiConsumer<Professeur, String>)Professeur::setPrenom);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProfesseurId() {
		return _professeurId;
	}

	@Override
	public void setProfesseurId(long professeurId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_professeurId = professeurId;
	}

	@JSON
	@Override
	public String getNom() {
		if (_nom == null) {
			return "";
		}
		else {
			return _nom;
		}
	}

	@Override
	public void setNom(String nom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nom = nom;
	}

	@JSON
	@Override
	public String getPrenom() {
		if (_prenom == null) {
			return "";
		}
		else {
			return _prenom;
		}
	}

	@Override
	public void setPrenom(String prenom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prenom = prenom;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Professeur.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Professeur toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Professeur>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProfesseurImpl professeurImpl = new ProfesseurImpl();

		professeurImpl.setUuid(getUuid());
		professeurImpl.setProfesseurId(getProfesseurId());
		professeurImpl.setNom(getNom());
		professeurImpl.setPrenom(getPrenom());

		professeurImpl.resetOriginalValues();

		return professeurImpl;
	}

	@Override
	public Professeur cloneWithOriginalValues() {
		ProfesseurImpl professeurImpl = new ProfesseurImpl();

		professeurImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		professeurImpl.setProfesseurId(
			this.<Long>getColumnOriginalValue("professeurId"));
		professeurImpl.setNom(this.<String>getColumnOriginalValue("nom"));
		professeurImpl.setPrenom(this.<String>getColumnOriginalValue("prenom"));

		return professeurImpl;
	}

	@Override
	public int compareTo(Professeur professeur) {
		long primaryKey = professeur.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Professeur)) {
			return false;
		}

		Professeur professeur = (Professeur)object;

		long primaryKey = professeur.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Professeur> toCacheModel() {
		ProfesseurCacheModel professeurCacheModel = new ProfesseurCacheModel();

		professeurCacheModel.uuid = getUuid();

		String uuid = professeurCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			professeurCacheModel.uuid = null;
		}

		professeurCacheModel.professeurId = getProfesseurId();

		professeurCacheModel.nom = getNom();

		String nom = professeurCacheModel.nom;

		if ((nom != null) && (nom.length() == 0)) {
			professeurCacheModel.nom = null;
		}

		professeurCacheModel.prenom = getPrenom();

		String prenom = professeurCacheModel.prenom;

		if ((prenom != null) && (prenom.length() == 0)) {
			professeurCacheModel.prenom = null;
		}

		return professeurCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Professeur, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Professeur, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Professeur, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Professeur)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Professeur>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Professeur.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _professeurId;
	private String _nom;
	private String _prenom;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Professeur, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Professeur)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("professeurId", _professeurId);
		_columnOriginalValues.put("nom", _nom);
		_columnOriginalValues.put("prenom", _prenom);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("professeurId", 2L);

		columnBitmasks.put("nom", 4L);

		columnBitmasks.put("prenom", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Professeur _escapedModel;

}