/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package professeur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Professeur service. Represents a row in the &quot;LL_Professeur&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>professeur.model.impl.ProfesseurModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>professeur.model.impl.ProfesseurImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Professeur
 * @generated
 */
@ProviderType
public interface ProfesseurModel extends BaseModel<Professeur> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a professeur model instance should use the {@link Professeur} interface instead.
	 */

	/**
	 * Returns the primary key of this professeur.
	 *
	 * @return the primary key of this professeur
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this professeur.
	 *
	 * @param primaryKey the primary key of this professeur
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this professeur.
	 *
	 * @return the uuid of this professeur
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this professeur.
	 *
	 * @param uuid the uuid of this professeur
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the professeur ID of this professeur.
	 *
	 * @return the professeur ID of this professeur
	 */
	public long getProfesseurId();

	/**
	 * Sets the professeur ID of this professeur.
	 *
	 * @param professeurId the professeur ID of this professeur
	 */
	public void setProfesseurId(long professeurId);

	/**
	 * Returns the nom of this professeur.
	 *
	 * @return the nom of this professeur
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this professeur.
	 *
	 * @param nom the nom of this professeur
	 */
	public void setNom(String nom);

	/**
	 * Returns the prenom of this professeur.
	 *
	 * @return the prenom of this professeur
	 */
	@AutoEscape
	public String getPrenom();

	/**
	 * Sets the prenom of this professeur.
	 *
	 * @param prenom the prenom of this professeur
	 */
	public void setPrenom(String prenom);

	@Override
	public Professeur cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}