/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package classe.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Classe service. Represents a row in the &quot;LL_Classe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>classe.model.impl.ClasseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>classe.model.impl.ClasseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Classe
 * @generated
 */
@ProviderType
public interface ClasseModel extends BaseModel<Classe> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a classe model instance should use the {@link Classe} interface instead.
	 */

	/**
	 * Returns the primary key of this classe.
	 *
	 * @return the primary key of this classe
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this classe.
	 *
	 * @param primaryKey the primary key of this classe
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this classe.
	 *
	 * @return the uuid of this classe
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this classe.
	 *
	 * @param uuid the uuid of this classe
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the classe ID of this classe.
	 *
	 * @return the classe ID of this classe
	 */
	public long getClasseId();

	/**
	 * Sets the classe ID of this classe.
	 *
	 * @param classeId the classe ID of this classe
	 */
	public void setClasseId(long classeId);

	/**
	 * Returns the intitule of this classe.
	 *
	 * @return the intitule of this classe
	 */
	@AutoEscape
	public String getIntitule();

	/**
	 * Sets the intitule of this classe.
	 *
	 * @param Intitule the intitule of this classe
	 */
	public void setIntitule(String Intitule);

	@Override
	public Classe cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}