/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fichiermatiere.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import fichiermatiere.model.FichierMatiere;
import fichiermatiere.model.FichierMatiereModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FichierMatiere service. Represents a row in the &quot;LL_FichierMatiere&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FichierMatiereModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FichierMatiereImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FichierMatiereImpl
 * @generated
 */
@JSON(strict = true)
public class FichierMatiereModelImpl
	extends BaseModelImpl<FichierMatiere> implements FichierMatiereModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fichier matiere model instance should use the <code>FichierMatiere</code> interface instead.
	 */
	public static final String TABLE_NAME = "LL_FichierMatiere";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"fichierMatiereId", Types.BIGINT},
		{"matiereId", Types.BIGINT}, {"fichierId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fichierMatiereId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("matiereId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fichierId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LL_FichierMatiere (uuid_ VARCHAR(75) null,fichierMatiereId LONG not null primary key,matiereId LONG,fichierId LONG)";

	public static final String TABLE_SQL_DROP = "drop table LL_FichierMatiere";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fichierMatiere.fichierMatiereId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LL_FichierMatiere.fichierMatiereId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FICHIERMATIEREID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FichierMatiereModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fichierMatiereId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFichierMatiereId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fichierMatiereId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FichierMatiere.class;
	}

	@Override
	public String getModelClassName() {
		return FichierMatiere.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FichierMatiere, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FichierMatiere, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FichierMatiere, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FichierMatiere)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FichierMatiere, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FichierMatiere, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FichierMatiere)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FichierMatiere, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FichierMatiere, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FichierMatiere, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FichierMatiere, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<FichierMatiere, Object>>();

			attributeGetterFunctions.put("uuid", FichierMatiere::getUuid);
			attributeGetterFunctions.put(
				"fichierMatiereId", FichierMatiere::getFichierMatiereId);
			attributeGetterFunctions.put(
				"matiereId", FichierMatiere::getMatiereId);
			attributeGetterFunctions.put(
				"fichierId", FichierMatiere::getFichierId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FichierMatiere, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FichierMatiere, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<FichierMatiere, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<FichierMatiere, String>)FichierMatiere::setUuid);
			attributeSetterBiConsumers.put(
				"fichierMatiereId",
				(BiConsumer<FichierMatiere, Long>)
					FichierMatiere::setFichierMatiereId);
			attributeSetterBiConsumers.put(
				"matiereId",
				(BiConsumer<FichierMatiere, Long>)FichierMatiere::setMatiereId);
			attributeSetterBiConsumers.put(
				"fichierId",
				(BiConsumer<FichierMatiere, Long>)FichierMatiere::setFichierId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFichierMatiereId() {
		return _fichierMatiereId;
	}

	@Override
	public void setFichierMatiereId(long fichierMatiereId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fichierMatiereId = fichierMatiereId;
	}

	@JSON
	@Override
	public long getMatiereId() {
		return _matiereId;
	}

	@Override
	public void setMatiereId(long matiereId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_matiereId = matiereId;
	}

	@JSON
	@Override
	public long getFichierId() {
		return _fichierId;
	}

	@Override
	public void setFichierId(long fichierId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fichierId = fichierId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FichierMatiere.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FichierMatiere toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FichierMatiere>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FichierMatiereImpl fichierMatiereImpl = new FichierMatiereImpl();

		fichierMatiereImpl.setUuid(getUuid());
		fichierMatiereImpl.setFichierMatiereId(getFichierMatiereId());
		fichierMatiereImpl.setMatiereId(getMatiereId());
		fichierMatiereImpl.setFichierId(getFichierId());

		fichierMatiereImpl.resetOriginalValues();

		return fichierMatiereImpl;
	}

	@Override
	public FichierMatiere cloneWithOriginalValues() {
		FichierMatiereImpl fichierMatiereImpl = new FichierMatiereImpl();

		fichierMatiereImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		fichierMatiereImpl.setFichierMatiereId(
			this.<Long>getColumnOriginalValue("fichierMatiereId"));
		fichierMatiereImpl.setMatiereId(
			this.<Long>getColumnOriginalValue("matiereId"));
		fichierMatiereImpl.setFichierId(
			this.<Long>getColumnOriginalValue("fichierId"));

		return fichierMatiereImpl;
	}

	@Override
	public int compareTo(FichierMatiere fichierMatiere) {
		long primaryKey = fichierMatiere.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FichierMatiere)) {
			return false;
		}

		FichierMatiere fichierMatiere = (FichierMatiere)object;

		long primaryKey = fichierMatiere.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FichierMatiere> toCacheModel() {
		FichierMatiereCacheModel fichierMatiereCacheModel =
			new FichierMatiereCacheModel();

		fichierMatiereCacheModel.uuid = getUuid();

		String uuid = fichierMatiereCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			fichierMatiereCacheModel.uuid = null;
		}

		fichierMatiereCacheModel.fichierMatiereId = getFichierMatiereId();

		fichierMatiereCacheModel.matiereId = getMatiereId();

		fichierMatiereCacheModel.fichierId = getFichierId();

		return fichierMatiereCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FichierMatiere, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FichierMatiere, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FichierMatiere, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FichierMatiere)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FichierMatiere>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FichierMatiere.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _fichierMatiereId;
	private long _matiereId;
	private long _fichierId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FichierMatiere, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FichierMatiere)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("fichierMatiereId", _fichierMatiereId);
		_columnOriginalValues.put("matiereId", _matiereId);
		_columnOriginalValues.put("fichierId", _fichierId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("fichierMatiereId", 2L);

		columnBitmasks.put("matiereId", 4L);

		columnBitmasks.put("fichierId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FichierMatiere _escapedModel;

}