/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fichiermatiere.model.impl;

import fichiermatiere.model.FichierMatiere;

import fichiermatiere.service.FichierMatiereLocalServiceUtil;

/**
 * The extended model base implementation for the FichierMatiere service. Represents a row in the &quot;LL_FichierMatiere&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FichierMatiereImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FichierMatiereImpl
 * @see FichierMatiere
 * @generated
 */
public abstract class FichierMatiereBaseImpl
	extends FichierMatiereModelImpl implements FichierMatiere {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fichier matiere model instance should use the <code>FichierMatiere</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FichierMatiereLocalServiceUtil.addFichierMatiere(this);
		}
		else {
			FichierMatiereLocalServiceUtil.updateFichierMatiere(this);
		}
	}

}