/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package professeur.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import professeur.model.ProfClasse;

import professeur.service.ProfClasseService;
import professeur.service.ProfClasseServiceUtil;
import professeur.service.persistence.ProfClassePersistence;
import professeur.service.persistence.ProfesseurPersistence;

/**
 * Provides the base implementation for the prof classe remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link professeur.service.impl.ProfClasseServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see professeur.service.impl.ProfClasseServiceImpl
 * @generated
 */
public abstract class ProfClasseServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, ProfClasseService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ProfClasseService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ProfClasseServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		ProfClasseServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ProfClasseService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		profClasseService = (ProfClasseService)aopProxy;

		ProfClasseServiceUtil.setService(profClasseService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ProfClasseService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ProfClasse.class;
	}

	protected String getModelClassName() {
		return ProfClasse.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = profClassePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected professeur.service.ProfClasseLocalService profClasseLocalService;

	protected ProfClasseService profClasseService;

	@Reference
	protected ProfClassePersistence profClassePersistence;

	@Reference
	protected ProfesseurPersistence professeurPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		ProfClasseServiceBaseImpl.class);

}